[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Syncify Documentation"
authors = [{name = "Syncify AB", email = "kundsupport@syncify.se"}]
dynamic = ["version", "description"]
